name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

env:
  IMAGE_NAME: "cvfuhr/codenoob-social-profile-frontend"
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
  MARVEL_PRIVATE_KEY: ${{ secrets.MARVEL_PRIVATE_KEY }}
  MARVEL_PUBLIC_KEY: ${{ secrets.MARVEL_PUBLIC_KEY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure Kubernetes credentials
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config          

      - name: Build and push image
        run: |
          docker build \
            --build-arg MARVEL_PRIVATE_KEY=${MARVEL_PRIVATE_KEY} \
            --build-arg MARVEL_PUBLIC_KEY=${MARVEL_PUBLIC_KEY} \
            -t codenoob-social-profile-frontend:${{ github.sha }} .
          docker tag codenoob-social-profile-frontend:${{ github.sha }} ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push  ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/socialfrontend socialfrontend=${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
