name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "cvfuhr/social-base"
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      MARVEL_PRIVATE_KEY: ${{ secrets.MARVEL_PRIVATE_KEY }}
      MARVEL_PUBLIC_KEY: ${{ secrets.MARVEL_PUBLIC_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          docker build -t social-base .
          docker tag social-base:latest ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
          docker push  ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
